// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1cDptesqhcZ-Mud3HRCtAIuld8RIJPeE',
    appId: '1:843780884679:web:d8a44c6b5d172dfa6596e2',
    messagingSenderId: '843780884679',
    projectId: 'foodorderingapp-a8ecb',
    authDomain: 'foodorderingapp-a8ecb.firebaseapp.com',
    storageBucket: 'foodorderingapp-a8ecb.appspot.com',
    measurementId: 'G-9B1SFCWGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEMzzQF-KwIQ4UG_Oegse0TBomDUb6kU',
    appId: '1:843780884679:android:618527e7c0791c0e6596e2',
    messagingSenderId: '843780884679',
    projectId: 'foodorderingapp-a8ecb',
    storageBucket: 'foodorderingapp-a8ecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0fhS-l8_lFijRn_yvqVjYCe4hvZAt4Gg',
    appId: '1:843780884679:ios:32f8b5d032471f8c6596e2',
    messagingSenderId: '843780884679',
    projectId: 'foodorderingapp-a8ecb',
    storageBucket: 'foodorderingapp-a8ecb.appspot.com',
    iosClientId: '843780884679-d9tepm56soq9p1eearltolap37p4f2al.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
